<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Tue Jun 30 16:50:11 KST 2020.

define('DOMJUDGE_VERSION', '7.3.0');

define('BINDIR',      '/home/oem/domjudge/domserver/bin');
define('ETCDIR',      '/home/oem/domjudge/domserver/etc');
define('WEBAPPDIR',   '/home/oem/domjudge/domserver/webapp');
define('LIBDIR',      '/home/oem/domjudge/domserver/lib');
define('SQLDIR',      '/home/oem/domjudge/domserver/sql');
define('LIBVENDORDIR','/home/oem/domjudge/domserver/lib/vendor');
define('LOGDIR',      '/home/oem/domjudge/domserver/log');
define('RUNDIR',      '/home/oem/domjudge/domserver/run');
define('TMPDIR',      '/home/oem/domjudge/domserver/tmp');

define('BASEURL',     'https://example.com/domjudge/');

define('SUBMITCLIENT_ENABLED', 'yes');
