# Generated by Django 3.0.5 on 2020-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pw', models.CharField(max_length=100)),
                ('dist_num', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
    ]
